import { Prisma } from '@grims/db';
import type { AclBoundClient } from '../authz/acl-db.service.js';

/**
 * Forum search (P2.5, INV-024).
 *
 * ★ THE INVARIANT IS ABOUT *WHERE* THE FILTER RUNS ★
 *
 * INV-024: "Search results are ACL-filtered IN THE QUERY, never after retrieval. A Ring 0 search
 * for a term appearing only in Ring 2 content returns ZERO results — not a redacted result, and not
 * a result count."
 *
 * The obvious implementation searches, then drops what the caller may not see. It gives the right
 * ROWS and leaks anyway, through three doors:
 *
 *   the total     "1–10 of 47" when a caller may see 10 has already said 37 exist
 *   the facets    a count per board names boards the caller cannot open
 *   the pages     page 5 existing when page 1 held everything visible says the same thing
 *
 * So the predicate is part of the SQL, and the count is `count(*)` over that same filtered set.
 * There is no post-filter step anywhere in this file — which is the property to check when reading
 * it, because a `.filter()` after the query is exactly what the invariant forbids.
 *
 * ★ WHY RAW SQL, AND WHY THAT IS THE DANGEROUS PART ★
 *
 * Full-text ranking needs `ts_rank` and the generated `search_tsv` column, which Prisma cannot
 * express. A raw query BYPASSES the ACL extension — the thing that silently protects every other
 * read in the forum. So this file cannot rely on the bound client's magic and has to carry the
 * filter explicitly, in the WHERE clause, every time.
 *
 * That is why `visibleCategoryIds` is a required parameter rather than something resolved inside:
 * a caller must supply it, and passing an empty array means "sees nothing" rather than "no filter".
 * The failure mode of a forgotten filter is an empty result, not the whole forum.
 */

export interface SearchHit {
  readonly postId: string;
  readonly threadId: string;
  readonly threadTitle: string;
  readonly threadSlug: string;
  readonly categorySlug: string;
  readonly authorHandle: string;
  readonly createdAt: string;
  /** A short excerpt with the matched terms marked. Generated by Postgres, then escaped. */
  readonly snippet: string;
}

export interface SearchResult {
  readonly hits: readonly SearchHit[];
  /**
   * The total over the SAME filtered set.
   *
   * Not "how many matched" — how many matched AND are visible. A total computed before the ACL is
   * the leak INV-024 names first.
   */
  readonly total: number;
  readonly query: string;
}

/** Bounds. A search is a public-ish endpoint and both of these are load-bearing. */
const MAX_QUERY_CHARS = 200;
const PAGE_SIZE = 20;
const MAX_OFFSET = 500;

export class SearchService {
  /**
   * Searches posts the caller can see.
   *
   * @param visibleCategoryIds Resolved from the caller's mask by `AclDbService`. REQUIRED — see the
   *        header. An empty array means the caller sees no boards, and therefore no results.
   * @param userId The caller, for per-thread grants. `null` for an anonymous visitor.
   */
  async search(
    db: AclBoundClient,
    rawQuery: string,
    visibleCategoryIds: readonly string[],
    userId: string | null,
    offset = 0,
  ): Promise<SearchResult> {
    const query = rawQuery.trim().slice(0, MAX_QUERY_CHARS);

    /*
     * A short query is refused rather than run. Two characters against a full-text index over every
     * post is a scan that returns most of the forum, and the result would be useless to the person
     * who typed it as well as expensive for everybody else.
     */
    if (query.length < 3) {
      return { hits: [], total: 0, query };
    }

    /*
     * ★ AN EMPTY VISIBLE SET SHORT-CIRCUITS ★
     *
     * `= ANY('{}')` is false for every row, so the query would be correct anyway. Returning early
     * is about making the intent unmistakable at the top of the function: no visible boards, no
     * results, and no query at all.
     */
    if (visibleCategoryIds.length === 0) {
      return { hits: [], total: 0, query };
    }

    const safeOffset = Math.max(0, Math.min(MAX_OFFSET, Math.floor(offset)));

    /*
     * `websearch_to_tsquery` rather than `to_tsquery`.
     *
     * `to_tsquery` demands operator syntax and THROWS on ordinary input — a member typing
     * `bounty hunting` gets a syntax error, and one typing `!` gets a 500. `websearch_to_tsquery`
     * accepts what a person actually types, including quoted phrases and `-exclusions`, and never
     * throws. The query is still a bound parameter, so this is about usability rather than safety.
     */
    const rows = await db.$queryRaw<
      Array<{
        post_id: string;
        thread_id: string;
        thread_title: string;
        thread_slug: string;
        category_slug: string;
        author_handle: string;
        created_at: Date;
        snippet: string;
        total: bigint;
      }>
    >(Prisma.sql`
      WITH visible AS (
        SELECT
          p.id            AS post_id,
          t.id            AS thread_id,
          t.title         AS thread_title,
          t.slug          AS thread_slug,
          c.slug          AS category_slug,
          u.handle        AS author_handle,
          p.created_at    AS created_at,
          ts_rank(p.search_tsv, websearch_to_tsquery('english', ${query})) AS rank,
          ts_headline(
            'english', p.body_md, websearch_to_tsquery('english', ${query}),
            'MaxWords=28, MinWords=12, ShortWord=3, MaxFragments=1, StartSel=«, StopSel=»'
          ) AS snippet
        FROM forum_posts p
        JOIN forum_threads t ON t.id = p.thread_id
        JOIN forum_categories c ON c.id = t.category_id
        JOIN users u ON u.id = p.author_id
        WHERE
          p.search_tsv @@ websearch_to_tsquery('english', ${query})
          -- Soft-deleted content is not searchable (INV-022): a deleted post that turned up in
          -- search would make the deletion cosmetic.
          AND p.deleted_at IS NULL
          AND t.deleted_at IS NULL
          -- ★ THE ACL, IN THE QUERY ★
          --
          -- Inherited board visibility, OR an explicit per-thread grant for THIS caller. The same
          -- two clauses the Prisma predicate uses, because two different answers to "can they see
          -- it" is how a search leak starts.
          AND (
            t.category_id = ANY(${visibleCategoryIds}::uuid[])
            OR EXISTS (
              SELECT 1 FROM forum_thread_grants g
              WHERE g.thread_id = t.id AND g.user_id = ${userId}::uuid
            )
          )
          -- An anonymous caller additionally needs the thread PUBLISHED. Mirrors the narrowing half
          -- of the Prisma predicate; without it a public board's drafts would be searchable.
          AND (${userId}::uuid IS NOT NULL OR t.is_public = true)
      )
      SELECT
        post_id, thread_id, thread_title, thread_slug, category_slug,
        author_handle, created_at, snippet,
        -- The total over the SAME filtered set, computed in the same pass. A separate count query
        -- could disagree with the rows under concurrent writes, and "1-10 of 47" that does not
        -- match the list is the exact disclosure INV-024 is about.
        count(*) OVER () AS total
      FROM visible
      ORDER BY rank DESC, created_at DESC
      LIMIT ${PAGE_SIZE} OFFSET ${safeOffset}
    `);

    return {
      hits: rows.map((r) => ({
        postId: r.post_id,
        threadId: r.thread_id,
        threadTitle: r.thread_title,
        threadSlug: r.thread_slug,
        categorySlug: r.category_slug,
        authorHandle: r.author_handle,
        createdAt: r.created_at.toISOString(),
        snippet: r.snippet,
      })),
      /*
       * `count(*) OVER ()` is absent when there are no rows, so zero results means zero total —
       * which is the answer INV-024 requires. There is deliberately no separate count query that
       * could report a number the rows do not support.
       */
      total: rows.length === 0 ? 0 : Number(rows[0]?.total ?? 0),
      query,
    };
  }
}

/**
 * Escapes a Postgres-generated snippet for display.
 *
 * ★ WHY THE MARKERS ARE ODD CHARACTERS ★
 *
 * `ts_headline` wraps matches in delimiters we choose. The obvious choice is `<b>`/`</b>` — and it
 * is wrong, because the snippet comes from `body_md`, which is a MEMBER'S TEXT. Emitting HTML
 * delimiters would mean the only way to render the highlight is to trust a string built from user
 * content, and any escaping applied afterwards would destroy the very tags we added.
 *
 * So Postgres marks matches with `«` and `»` — characters that cannot appear in HTML syntax — the
 * whole snippet is escaped, and only THEN are the markers replaced with tags. Escape first, add
 * markup second, and there is no ordering in which member text becomes an element.
 */
export function renderSnippet(snippet: string): string {
  const escaped = snippet
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

  return escaped.replace(/«/g, '<mark>').replace(/»/g, '</mark>');
}
