import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * Shared ESLint flat config.
 *
 * The three project-specific rules below are not style preferences — each one
 * enforces a rule from ssot/CONVENTIONS.md or a security invariant, and each has
 * bitten a real project before.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      // The verification build (pnpm build:check) writes here so it cannot
      // disturb a running dev server. Same generated output as .next, so it
      // needs the same exemption — otherwise linting a production bundle
      // reports hundreds of errors in code nobody wrote.
      '**/.next-check/**',
      '**/node_modules/**',
      '**/coverage/**',
      // Gitignored working notes and throwaway probe scripts. Not shipped, not reviewed, and
      // holding them to the repo's rules would mean a lint failure for a script that existed to
      // answer one question and will be deleted.
      '**/.notes/**',
      // Generated by Next.js on every build and gitignored. Its triple-slash
      // reference is required by the framework and is not ours to change.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    rules: {
      // CONVENTIONS.md: `any` is banned. Use `unknown` + a Zod parse at the boundary.
      '@typescript-eslint/no-explicit-any': 'error',
      // CONVENTIONS.md: non-null assertion banned outside tests.
      '@typescript-eslint/no-non-null-assertion': 'error',
      // AGENTS.md 4: no bare catch that swallows.
      'no-empty': ['error', { allowEmptyCatch: false }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // CONVENTIONS.md: cross-package relative imports are a lint error.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../../packages/*', '../../../packages/*', '../../apps/*', '../../../apps/*'],
              message:
                'Cross-package relative import. Use the @grims/* alias instead (ssot/CONVENTIONS.md).',
            },
          ],
        },
      ],
      // INV-008: no Discord snowflake may be hard-coded. They live in role_mappings
      // as DATA. A literal here is how a test guild's IDs reach production.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/^[0-9]{17,20}$/]',
          message:
            'Looks like a hard-coded Discord snowflake. Role/guild IDs are data in role_mappings, never source (INV-008).',
        },
      ],
    },
  },
  {
    // Tests may assert on fixture IDs and use non-null assertions.
    files: ['**/*.spec.ts', '**/*.spec.tsx', '**/fixtures/**', '**/*.fixture.ts'],
    rules: {
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    /*
     * Build configuration files RUN IN NODE, whatever the app around them
     * targets. Linting next.config.mjs as browser-adjacent makes `process`
     * an undefined global — which is correct for application code and simply
     * wrong here, and the workaround is otherwise to contort the config to
     * avoid reading its own environment.
     *
     * Scoped to config files by name so application code keeps the strict
     * treatment: a stray `process.env` in a component is still an error, which
     * is the thing this rule is actually for.
     */
    // Listed one by one rather than with a {js,mjs,cjs} brace group: the
    // minimatch version resolved here throws "expand is not a function" on
    // brace expansion, and it fails as an ESLint crash rather than a lint
    // error, which reads like a broken install.
    files: [
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.cjs',
      '**/*.config.ts',
      '**/*.config.mts',
      // Build and launch scripts. They are Node programs that happen not to be
      // called *.config.* — same environment, same globals.
      //
      // Each launcher has to be named here. `prod.mjs` was added and promptly
      // failed lint on `process` and `console`, because the list is explicit by
      // design — see the brace-expansion note above. Anything new that spawns
      // Electron or drives a build belongs in this list.
      '**/build.mjs',
      '**/dev.mjs',
      '**/prod.mjs',
      '**/make-icons.mjs',
      // Refuses `next build` while the dev server is up. Added 2026-08-03 and it failed lint on
      // `process` and `console` exactly as `prod.mjs` did — which is the third time this list has
      // proved it is explicit by design rather than by accident.
      '**/prebuild.mjs',
      // Supervises the resident ingestion services in development, because turbo starts them once
      // and a dead EDDN subscriber is invisible. Fourth entry, failing on the same two globals as
      // every one before it — the list is explicit by design, and this is the design working.
      '**/keep-alive.mjs',
      // The changelog generator runs as `node tools/changelog.mjs` on the
      // production box during a deploy — plain Node, no build step — so it
      // reads process.argv and prints like every launcher above it.
      '**/changelog.mjs',
    ],
    languageOptions: {
      globals: {
        process: 'readonly',
        __dirname: 'readonly',
        module: 'writable',
        Buffer: 'readonly',
        // A launch script that cannot say what it is doing is a launch script
        // nobody can debug. `dev.mjs` never printed anything, so this was
        // missing until a launcher needed to announce which hub it had chosen.
        console: 'readonly',
        // A supervisor's whole job is to wait before trying again. Absent until one needed it.
        setTimeout: 'readonly',
      },
    },
  },
);
