import { AppError, ErrorCode, Permission } from '@grims/shared';
import type { PrismaClient } from '@grims/db';
import type { ObjectStore } from './object-store.js';
import { hardenImage, ImageRejected, MAX_UPLOAD_BYTES } from './image-hardening.js';

/**
 * Accepting an image and serving it back.
 *
 * ★ THE DIVISION OF LABOUR ★
 *
 *   image-hardening.ts  decides WHAT the bytes are — decodes and re-encodes, so nothing
 *                       from the original container survives.
 *   sanitize.ts         decides WHERE a post may reference an image from — a relative
 *                       path under our own media route, never a remote host.
 *   this file           decides WHO may upload, and mints the id that ties the two
 *                       together.
 *
 * None of the three is sufficient alone, and each is testable without the others.
 *
 * ★ THE STORAGE KEY IS OURS, END TO END ★
 *
 * The client sends bytes. It does not send a filename, and if it did, nothing here would
 * read it. The key is `uploads/<uuid>.<ext>` where the uuid is generated by the database
 * and the extension comes from the format WE encoded — so there is no path a caller can
 * influence, and therefore no traversal to defend against. That is cheaper than
 * sanitising a filename and it cannot be got wrong later.
 */

/**
 * Who may upload.
 *
 * `FORUM_POST_MEMBER` — if you can write a post, you can put a screenshot in it. Anything
 * narrower would mean members could describe a bug but not show it, and the guides board
 * needs `FORUM_POST_GUIDE` holders to upload anyway, which is a superset in practice.
 *
 * NOT anonymous, and that is the load-bearing part: `uploader_id` is NOT NULL, storage
 * costs money, and an unauthenticated upload endpoint is a free file host attached to our
 * domain.
 */
const UPLOAD_PERMISSION = Permission.FORUM_POST_MEMBER;

/**
 * How many images one member may upload per day.
 *
 * Not a security boundary — somebody determined can post 200 screenshots — but it bounds
 * the damage from a script, and an accidental loop is far more likely than an attack. A
 * member who legitimately needs more than this in a day should be talking to an officer
 * about what they are doing.
 */
const DAILY_UPLOAD_LIMIT = 200;

export interface UploadResult {
  readonly id: string;
  /**
   * The path to put in Markdown. RELATIVE, deliberately — see `isOwnMediaSrc`: the
   * sanitiser accepts only relative paths, so returning an absolute URL here would
   * hand the client something the sanitiser then refuses.
   */
  readonly path: string;
  readonly width: number;
  readonly height: number;
  readonly bytes: number;
}

export interface ServedUpload {
  readonly body: Uint8Array;
  readonly contentType: string;
}

const EXTENSION: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/webp': 'webp',
};

export class UploadService {
  constructor(
    private readonly objects: ObjectStore,
    private readonly db: PrismaClient,
  ) {}

  /**
   * Hardens an upload and stores it.
   *
   * ★ THE ORDER OF OPERATIONS IS THE INTERESTING PART ★
   *
   * Permission, then quota, then harden, then store, then record. Each step is cheaper
   * than the one after it, so a caller who fails the first never costs us a decode — and
   * the decode is by far the most expensive thing here, which makes it exactly what an
   * unauthenticated attacker would aim at.
   */
  async upload(
    uploaderId: string,
    callerMask: bigint,
    bytes: Uint8Array,
  ): Promise<UploadResult> {
    if ((callerMask & UPLOAD_PERMISSION) !== UPLOAD_PERMISSION) {
      throw new AppError(ErrorCode.PERMISSION_DENIED, 'You cannot upload images yet.');
    }

    /*
     * Counted over a rolling 24 hours rather than "today", so the limit cannot be
     * doubled by uploading either side of midnight.
     */
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const recent = await this.db.mediaUpload.count({
      where: { uploaderId, createdAt: { gte: since } },
    });
    if (recent >= DAILY_UPLOAD_LIMIT) {
      throw new AppError(
        ErrorCode.RATE_LIMITED,
        `That is ${DAILY_UPLOAD_LIMIT} images in a day, which is more than anybody needs by accident. Try again tomorrow, or ask an officer.`,
      );
    }

    let hardened;
    try {
      hardened = await hardenImage(bytes);
    } catch (err) {
      if (err instanceof ImageRejected) {
        // The member-facing message from the hardener, which already says what to do.
        throw new AppError(ErrorCode.VALIDATION_FAILED, err.message);
      }
      throw err;
    }

    /*
     * ★ THE ROW IS CREATED FIRST, TO MINT THE ID THAT NAMES THE OBJECT ★
     *
     * The key must contain the id, and the id comes from the database default. So the row
     * is inserted with a placeholder key and updated once the real key is known.
     *
     * The alternative — generate a uuid in application code — avoids the update but puts
     * id generation in two places, and the two would eventually disagree about format.
     * One extra UPDATE on an upload that just did an image decode is not worth optimising.
     *
     * If the PUT then fails, the row is deleted. An orphaned ROW pointing at a
     * non-existent object renders as a broken image forever; an orphaned OBJECT is dead
     * bytes nobody references. Given a choice, leak the bytes.
     */
    const ext = EXTENSION[hardened.contentType] ?? 'bin';

    const row = await this.db.mediaUpload.create({
      data: {
        uploaderId,
        // Unique and obviously provisional: if this is ever observed in the database, the
        // update below did not run and that is a bug rather than a state to interpret.
        storageKey: `pending/${uploaderId}/${Date.now()}-${recent}`,
        contentType: hardened.contentType,
        bytes: hardened.body.byteLength,
        width: hardened.width,
        height: hardened.height,
      },
      select: { id: true },
    });

    const key = `uploads/${row.id}.${ext}`;

    try {
      await this.objects.put(key, hardened.body, hardened.contentType);
      await this.db.mediaUpload.update({ where: { id: row.id }, data: { storageKey: key } });
    } catch (err) {
      await this.db.mediaUpload.delete({ where: { id: row.id } }).catch(() => undefined);
      throw err;
    }

    return {
      id: row.id,
      path: `/v1/media/uploads/${row.id}`,
      width: hardened.width,
      height: hardened.height,
      bytes: hardened.body.byteLength,
    };
  }

  /**
   * Serves an upload by id.
   *
   * ★ NO ACL CHECK HERE, AND THAT IS A DECISION RATHER THAN AN OMISSION ★
   *
   * An image is readable by anyone who has its id. The id is a UUID, so it is
   * unguessable, and it is only ever published inside a post — so in practice an image is
   * as private as the thread that references it.
   *
   * The alternative is to resolve "which posts reference this image, and may the caller
   * read any of them" on every image request. That was considered and rejected:
   *
   *   - It is a join per image, on the hottest path in the application. A guide with
   *     twelve screenshots becomes twelve authorisation queries per page view.
   *   - `bodyHtml` is HTML, so "which posts reference this" means pattern-matching stored
   *     markup. A reference the matcher misses makes a legitimate image 404 — a guide
   *     with holes in it, reported as "the site is broken".
   *   - The same image can legitimately appear in a public guide AND an officers' thread,
   *     at which point the correct answer depends on which post the reader came from,
   *     which is not something an image request knows.
   *
   * What this DOES guarantee: an unguessable id, no directory listing, and no way to
   * enumerate. What it does not: an image whose id has leaked stays readable. That is the
   * same model every major forum uses, and it is stated here so nobody has to infer it.
   *
   * If an image ever needs to be genuinely secret, the answer is a signed, expiring URL —
   * a different feature, not a check bolted onto this one.
   */
  async serve(id: string): Promise<ServedUpload | null> {
    /*
     * Validated as a UUID before it reaches the database or the store. Prisma
     * parameterises, so this is not about injection — it is that `findUnique` on a
     * malformed uuid throws a Prisma error which would surface as a 500 instead of a 404.
     */
    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
      return null;
    }

    const row = await this.db.mediaUpload.findUnique({
      where: { id },
      select: { storageKey: true, contentType: true },
    });
    if (row === null) return null;

    const object = await this.objects.get(row.storageKey);
    if (object === null) return null;

    return {
      body: object.body,
      /*
       * The content type from OUR row, not from the object store's metadata. The row
       * records what we encoded; the store echoes back whatever it was told, which is one
       * indirection further from the thing we actually know.
       */
      contentType: row.contentType,
    };
  }
}

export { MAX_UPLOAD_BYTES, DAILY_UPLOAD_LIMIT, UPLOAD_PERMISSION };
