import type { PrismaClient } from '@grims/db';
import { logger } from '../logging.js';

/**
 * One deployed release, as the page consumes it.
 *
 * `deployedAt` travels as an ISO string: the web page formats it in the
 * member's own timezone AND UTC (INV-025), and a string is the only shape
 * JSON can carry an instant in without lying about its type.
 */
export interface ChangelogRelease {
  readonly id: string;
  readonly fromSha: string;
  readonly toSha: string;
  readonly deployedAt: string;
  readonly websiteMd: string;
  readonly companionMd: string;
  readonly platformMd: string;
}

interface ReleaseRow {
  id: string;
  fromSha: string;
  toSha: string;
  version: string | null;
  deployedAt: Date;
  websiteMd: string;
  companionMd: string;
  platformMd: string;
}

/**
 * Reads the changelog ledger.
 *
 * ★ RAW SQL, AND WHY THAT IS THE RIGHT TOOL HERE ★
 *
 * `changelog_releases` was added to the schema in the same change as this
 * store, and the Prisma CLIENT is regenerated by the operator (with the API
 * stopped — the engine DLL cannot be replaced under a running process), not
 * by the code that ships a feature. A typed `prisma.changelogRelease` call
 * would therefore fail to COMPILE until an operator step that happens after
 * merge. `$queryRaw` compiles today, runs identically once the migration is
 * applied, and this table is one SELECT with no relations — the typed client
 * would buy nothing here anyway. If the model ever grows relations, migrate
 * to the generated delegate then.
 */
export class ChangelogStore {
  constructor(private readonly db: PrismaClient) {}

  /**
   * Every recorded release, newest first.
   *
   * Capped at fifty: the page is "what changed lately", not an archive, and
   * fifty deploys of prose is already more than anybody scrolls. The full
   * history stays in the table and in git.
   */
  async releases(): Promise<ChangelogRelease[]> {
    let rows: ReleaseRow[];
    try {
      rows = await this.db.$queryRaw<ReleaseRow[]>`
        SELECT id,
               from_sha     AS "fromSha",
               to_sha       AS "toSha",
               version,
               deployed_at  AS "deployedAt",
               website_md   AS "websiteMd",
               companion_md AS "companionMd",
               platform_md  AS "platformMd"
          FROM changelog_releases
         ORDER BY deployed_at DESC, id
         LIMIT 50`;
    } catch (err) {
      /*
       * 42P01 is "relation does not exist" — a database the migration has not
       * reached yet, which is every dev database between pulling this change
       * and running migrate. An empty changelog is the truthful answer there
       * ("nothing recorded"), where a 500 would read as the feature being
       * broken. Any OTHER failure still throws: a connection problem must not
       * masquerade as an empty history.
       */
      const code = (err as { meta?: { code?: string } }).meta?.code;
      if (code === '42P01') {
        logger.warn('changelog_releases does not exist yet — run the migration; serving an empty list');
        return [];
      }
      throw err;
    }

    return rows.map((row) => ({
      ...row,
      deployedAt: row.deployedAt.toISOString(),
    }));
  }
}
